using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FireEmblem
{
    public static class Info
    {
        public static Dictionary<CharacterName, Dictionary<ClassName, Texture2D>> Images = new Dictionary<CharacterName, Dictionary<ClassName, Texture2D>>();
        public static Dictionary<ClassName, Dictionary<Team, Dictionary<AnimationName, Animation>>> Animations = new Dictionary<ClassName, Dictionary<Team, Dictionary<AnimationName, Animation>>>();

        public static Dictionary<ItemName, Item> Items = new Dictionary<ItemName, Item>()
        {
            { ItemName.DoorKey,         new Item("Door Key",        1, 300, ItemType.Ect)},
            { ItemName.ChestKey,        new Item("Chest Key",       1, 300, ItemType.Ect)},
            { ItemName.MasterKey,       new Item("Master Key",      1, 500, ItemType.Ect)},
            { ItemName.SmallBullion,    new Item("Bullion (S)",     1, 2000, ItemType.Ect)},
            { ItemName.MediumBullion,   new Item("Bullion (M)",     1, 10000, ItemType.Ect)},
            { ItemName.LargeBullion,    new Item("Bullion (L)",     1, 20000, ItemType.Ect)},
            { ItemName.ReekingBox,      new Item("Reeking Box",     1, 500, ItemType.Ect) },
            { ItemName.RiftDoor,        new Item("Rift Door",       1,1000, ItemType.Ect) },
            { ItemName.SupremeEmblem,   new Item("Supreme Emblem",  1,99999, ItemType.Ect) },
            { ItemName.DreadScroll,     new Item("Dread Scroll",    1, 0, ItemType.Ect)},
            { ItemName.WeddingBouquet,  new Item("WeddingBouquet",  1, 0, ItemType.Ect)},
            { ItemName.Paragon,         new Item("Paragon",         1, 0, ItemType.Ect)},
            { ItemName.IotesShield,     new Item("Iote's Shield",   1, 0, ItemType.Ect)},
            { ItemName.SilverCard,      new Item("Silver Card",     1, 0, ItemType.Ect)},
            { ItemName.OutrealmItem,    new Item("Outrealm Item",   1, 0, ItemType.Ect)},

            { ItemName.Vulnerary,       new HealthItem("Vulnerary",     0, 0, 10, 3, 300) },
            { ItemName.Concoction,      new HealthItem("Concoction",    0, 0, 20, 3, 600) },
            { ItemName.Elixir,          new HealthItem("Elixir",        0, 0, 100.0f, 3, 900) },
            { ItemName.SweetTincture,   new HealthItem("Sweet Tincture",0, 0, 5, 3, 150) },

            { ItemName.PureWater,       new StatItem("Pure Water",      0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 5, 0), 3, 600, false, 1) },
            { ItemName.HPTonic,         new StatItem("HP Tonic",        0, 0, new CharacterStatistics(5, 0, 0, 0, 0, 0, 0, 0, 0), 1, 150, false, 0) },
            { ItemName.StrengthTonic,   new StatItem("Strength Tonic",  0, 0, new CharacterStatistics(0, 2, 0, 0, 0, 0, 0, 0, 0), 1, 150, false, 0) },
            { ItemName.MagicTonic,      new StatItem("Magic Tonic",     0, 0, new CharacterStatistics(0, 0, 2, 0, 0, 0, 0, 0, 0), 1, 150, false, 0) },
            { ItemName.SkillTonic,      new StatItem("Skill Tonic",     0, 0, new CharacterStatistics(0, 0, 0, 2, 0, 0, 0, 0, 0), 1, 150, false, 0) },
            { ItemName.SpeedTonic,      new StatItem("Speed Tonic",     0, 0, new CharacterStatistics(0, 0, 0, 0, 2, 0, 0, 0, 0), 1, 150, false, 0) },
            { ItemName.LuckTonic,       new StatItem("Luck Tonic",      0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 2, 0, 0, 0), 1, 150, false, 0) },
            { ItemName.DefenceTonic,    new StatItem("Defence Tonic",   0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 2, 0, 0), 1, 150, false, 0) },
            { ItemName.ResistanceTonic, new StatItem("Resistance Tonic",0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 2, 0), 1, 150, false, 0) },
            { ItemName.SeraphRobe,      new StatItem("Seraph Robe",     0, 0, new CharacterStatistics(5, 0, 0, 0, 0, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.EnergyDrop,      new StatItem("Energy Drop",     0, 0, new CharacterStatistics(0, 2, 0, 0, 0, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.SpiritDust,      new StatItem("Spirit Dust",     0, 0, new CharacterStatistics(0, 0, 2, 0, 0, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.SecretBook,      new StatItem("Secret Book",     0, 0, new CharacterStatistics(0, 0, 0, 2, 0, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.Speedwing,       new StatItem("Speedwing",       0, 0, new CharacterStatistics(0, 0, 0, 0, 2, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.GoddessIcon,     new StatItem("Goddess Icon",    0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 2, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.Dracoshield,     new StatItem("Dracoshield",     0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 2, 0, 0), 1,2500, true,  0) },
            { ItemName.Talisman,        new StatItem("Talisman",        0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 2, 0), 1,2500, true,  0) },
            { ItemName.NagasTear,       new StatItem("Naga's Tear",     0, 0, new CharacterStatistics(5, 2, 2, 2, 2, 2, 2, 2, 2), 1,5000, true,  0) },
            { ItemName.Boots,           new StatItem("Boots",           0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 0, 2), 1,2500, true,  0) },
            { ItemName.ArmsScroll,      new StatItem("Arms Scroll",     0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.MasterSeal,      new StatItem("Master Seal",     0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.SecondSeal,      new StatItem("Second Seal",     0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 0, 0), 1,2500, true,  0) },
            { ItemName.GaiussConfect,   new StatItem("Gaius's Confect", 0, 0, new CharacterStatistics(0, 2, 0, 2, 2, 0, 0, 0, 0), 1,2000, false, 0) },
            { ItemName.KrissConfect,    new StatItem("Kris's Confect",  0, 0, new CharacterStatistics(5, 0, 0, 0, 0, 0, 2, 2, 0), 1,1000, false, 0) },
            { ItemName.SeedofTrust,     new StatItem("Seed of Trust",   0, 0, new CharacterStatistics(0, 0, 0, 0, 0, 0, 0, 0, 0), 1,1000, true,  0) },
            { ItemName.AllStats,        new StatItem("All Stats +2",    0, 0, new CharacterStatistics(2, 2, 2, 2, 2, 2, 2, 2, 2), 1, 0, true, 0) },

            { ItemName.BronzeSword,       new Weapon("Bronze Sword",      'E', 3, 100,0, 1, 1, new UnitType[] {},                                             50,350,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.IronSword,         new Weapon("Iron Sword",        'D', 5, 95, 0, 1, 1, new UnitType[] {},                                             40,520,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.SteelSword,        new Weapon("Steel Sword",       'C', 8, 90, 0, 1, 1, new UnitType[] {},                                             35,840,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.SilverSword,       new Weapon("Silver Sword",      'B', 11,85, 0, 1, 1, new UnitType[] {},                                             30,1410, 1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.BraveSword,        new Weapon("Brave Sword",       'A', 9, 80, 0, 1, 1, new UnitType[] {},                                             30,2100, 2,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.Armourslayer,      new Weapon("Armourslayer",      'D', 8, 80, 0, 1, 1, new UnitType[] { UnitType.Armored },                           25,1450, 1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.Wyrmslayer,        new Weapon("Wyrmslayer",        'D', 8, 80, 0, 1, 1, new UnitType[] { UnitType.Dragons },                           25,1500, 1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.KillingEdge,       new Weapon("Killing Edge",      'C', 9, 90, 30,1, 1, new UnitType[] {},                                             30,1470, 1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.LevinSword,        new Weapon("Levin Sword",       'C', 10,80, 0, 1, 2, new UnitType[] {},                                             25,1600, 1,                     new CharacterStatistics(), WeaponType.Sword){isPhysical = false} },
            { ItemName.Rapier,            new Weapon("Rapier",            'E', 5, 90, 10,1, 1, new UnitType[] { UnitType.Beasts, UnitType.Armored },          35,1600, 1,                     new CharacterStatistics(), WeaponType.Sword, new ClassName[] { ClassName.Lord, ClassName.GreatLord }) },
            { ItemName.NobleRapier,       new Weapon("Noble Rapier",      'C', 8, 85, 10,1, 1, new UnitType[] { UnitType.Beasts, UnitType.Armored },          25,2100, 1,                     new CharacterStatistics(), WeaponType.Sword, new ClassName[] { ClassName.Lord, ClassName.GreatLord }) },
            { ItemName.Missiletainn,      new Weapon("Missiletainn",      'C', 8, 85, 10,1, 1, new UnitType[] {},                                             35,1050, 1,                     new CharacterStatistics(0,0,0,1,0,0,0,0), WeaponType.Sword) },
            { ItemName.Sol,               new Weapon("Sol",               'B', 12,85, 5, 1, 1, new UnitType[] {},                                             30,0,    1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.Amatsu,            new Weapon("Amatsu",            'A', 12,60, 5, 1, 2, new UnitType[] {},                                             30,0,    1,                     new CharacterStatistics(), WeaponType.Sword, new ClassName[] { ClassName.Myrmidon, ClassName.Swordmaster }) },
            { ItemName.Falchion,          new Weapon("Falchion",          'E', 5, 80, 0, 1, 1, new UnitType[] { UnitType.Dragons },                           -1,-1,   1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.ExaltedFalchion,   new Weapon("Exalted Falchion",  'E', 15,80, 10,1, 1, new UnitType[] { UnitType.Dragons, UnitType.FellDragons },     -1,-1,   1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.ParallelFalchion,  new Weapon("Parallel Falchion", 'E', 12,80, 5, 1, 1, new UnitType[] { UnitType.Dragons, UnitType.FellDragons },     -1,-1,   1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.Mercurius,         new Weapon("Mercurius",         'A', 17,95, 5, 1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.Tyfing,            new Weapon("Tyrfing",           'A', 15,85, 10,1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,0,0,0,5,0), WeaponType.Sword) },
            { ItemName.Balmung,           new Weapon("Balmung",           'A', 13,90, 10,1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,0,5,0,0,0), WeaponType.Sword) },
            { ItemName.Mystletainn,       new Weapon("Mystletainn",       'A', 14,85, 15,1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,5,0,0,0,0), WeaponType.Sword) },
            { ItemName.SolKatti,          new Weapon("Sol Katti",         'A', 8, 100,50,1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,0,0,0,5,0), WeaponType.Sword , new ClassName[] { ClassName.Swordmaster, ClassName.Myrmidon }) },
            { ItemName.Ragnell,           new Weapon("Ragnell",           'A', 15,70, 0, 1, 2, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,0,0,5,0,0), WeaponType.Sword) },
            { ItemName.TreeBranch,        new Weapon("Tree Branch",       'E', 1, 100,0, 1, 1, new UnitType[] {},                                             20,100,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.GlassSword,        new Weapon("Glass Sword",       'E', 11,85, 0, 1, 1, new UnitType[] {},                                             3, 600,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.SoothingSword,     new Weapon("Soothing Sword",    'D', 8, 85, 0, 1, 1, new UnitType[] {},                                             10,920,  1,                     new CharacterStatistics(), WeaponType.Sword) { SelfHeal = 10 } },
            { ItemName.SuperiorEdge,      new Weapon("Superior Edge",     'B', 11,80, 0, 1, 1, new UnitType[] {},                                             10,1950, 1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.LeifsBlade,        new Weapon("Leif's Blade",      'D', 4, 95, 30,1, 1, new UnitType[] {},                                             20,820,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.RoysBlade,         new Weapon("Roy's Blade",       'D', 8, 95, 5, 1, 1, new UnitType[] {},                                             25,900,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.EliwoodsBlade,     new Weapon("Eliwood's Blade",   'C', 10,85, 5, 1, 1, new UnitType[] {},                                             20,960,  1,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.EirikasBlade,      new Weapon("Eirika's Blade",    'C', 6, 95, 10,1, 1, new UnitType[] {},                                             20,1220, 2,                     new CharacterStatistics(), WeaponType.Sword) },
            { ItemName.SeliphsBlade,      new Weapon("Seliph's Blade",    'B', 12,90, 15,1, 1, new UnitType[] {},                                             15,1530, 1,                     new CharacterStatistics(0,0,0,0,2,0,2,0), WeaponType.Sword) },
            { ItemName.AlmsBlade,         new Weapon("Alm's Blade",       'B', 15,75, 10,1, 1, new UnitType[] {},                                             10,1630, 1,                     new CharacterStatistics(), WeaponType.Sword) },

            { ItemName.BronzeLance,       new Weapon("Bronze Lance",      'E', 3, 90, 0, 1, 1, new UnitType[] {},                                             50,350,  1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.IronLance,         new Weapon("Iron Lance",        'D', 6, 85, 0, 1, 1, new UnitType[] {},                                             40,560,  1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.SteelLance,        new Weapon("Steel Lance",       'C', 9, 80, 0, 1, 1, new UnitType[] {},                                             35,910,  1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.SilverLance,       new Weapon("Silver Lance",      'B', 13,75, 0, 1, 1, new UnitType[] {},                                             30,1560, 1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.BraveLance,        new Weapon("Brave Lance",       'A', 10,70, 0, 1, 1, new UnitType[] {},                                             30,2220, 2,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.Javelin,           new Weapon("Javelin",           'D', 2, 80, 0, 1, 2, new UnitType[] {},                                             25,700,  1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.ShortSpear,        new Weapon("Short Spear",       'C', 5, 75, 0, 1, 2, new UnitType[] {},                                             25,1600, 1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.Spear,             new Weapon("Spear",             'B', 8, 70, 0, 1, 2, new UnitType[] {},                                             25,2400, 1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.BeastKiller,       new Weapon("Beast Killer",      'D', 9, 70, 0, 1, 1, new UnitType[] { UnitType.Beasts },                            25,1650, 1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.BlessedLance,      new Weapon("Blessed Lance",     'C', 11,70, 0, 1, 1, new UnitType[] { UnitType.Monsters },                          35,1540, 1,                     new CharacterStatistics(), WeaponType.Lance) { SelfHeal = 10 }  },
            { ItemName.KillerLance,       new Weapon("Killer Lance",      'C', 10,80, 30,1, 1, new UnitType[] {},                                             30,1680, 1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.Luna,              new Weapon("Luna",              'B', 14,80, 5, 1, 1, new UnitType[] {},                                             30,0,    1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.Gradivus,          new Weapon("Gradivus",          'A', 19,85, 5, 1, 2, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.GaeBolg,           new Weapon("Gáe Bolg",          'A', 15,75, 10,1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,0,0,5,0,0), WeaponType.Lance)  },
            { ItemName.Gungnir,           new Weapon("Gungnir",           'A', 16,70, 10,1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,5,0,0,0,0,0,0), WeaponType.Lance)  },
            { ItemName.Log,               new Weapon("Log",               'E', 1, 90, 0, 1, 1, new UnitType[] {},                                             20,100,  1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.GlassLance,        new Weapon("Glass Lance",       'E', 13,75, 0, 1, 1, new UnitType[] {},                                             3, 600,  1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.MiniatureLance,    new Weapon("Miniature Lance",   'D', 1, 55, 35,1, 2, new UnitType[] {},                                             10,650,  1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.Shockstick,        new Weapon("Shockstick",        'C', 11,85, 10,1, 1, new UnitType[] {},                                             20,1200, 1,                     new CharacterStatistics(), WeaponType.Lance) { isPhysical = false }  },
            { ItemName.SuperiorLance,     new Weapon("Superior Lance",    'B', 13,70, 0, 1, 1, new UnitType[] {},                                             10,2100, 1,                     new CharacterStatistics(), WeaponType.Lance)  },
            { ItemName.FinnsLance,        new Weapon("Finn's Lance",      'D', 8, 85, 10,1, 1, new UnitType[] {},                                             25,950,  1,                     new CharacterStatistics(0,0,0,0,0,2,2,0,0), WeaponType.Lance)  },
            { ItemName.EphraimsLance,     new Weapon("Ephraim's Lance",   'C', 11,80, 10,1, 1, new UnitType[] {},                                             20,1220, 1,                     new CharacterStatistics(0,2,0,0,2,0,0,0), WeaponType.Lance)  },
            { ItemName.SigurdsLance,      new Weapon("Sigurd's Lance",    'B', 14,85, 15,1, 1, new UnitType[] {},                                             15,1920, 1,                     new CharacterStatistics(), WeaponType.Lance)  },

            { ItemName.BronzeAxe,         new Weapon("Bronze Axe",        'E', 4, 80, 0, 1, 1, new UnitType[] {},                                             50,400,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.IronAxe,           new Weapon("Iron Axe",          'D', 7, 75, 0, 1, 1, new UnitType[] {},                                             40,600,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.SteelAxe,          new Weapon("Steel Axe",         'C', 11,70, 0, 1, 1, new UnitType[] {},                                             35,980,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.SilverAxe,         new Weapon("Silver Axe",        'B', 15,65, 0, 1, 1, new UnitType[] {},                                             30,1740, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.BraveAxe,          new Weapon("Brave Axe",         'A', 12,60, 0, 1, 1, new UnitType[] {},                                             30,2400, 2,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.HandAxe,           new Weapon("Hand Axe",          'D', 3, 70, 0, 1, 2, new UnitType[] {},                                             25,750,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.ShortAxe,          new Weapon("Short Axe",         'C', 7, 65, 0, 1, 2, new UnitType[] {},                                             25,1750, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.Tomahawk,          new Weapon("Tomahawk",          'B', 10,60, 0, 1, 2, new UnitType[] {},                                             25,2550, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.Hammer,            new Weapon("Hammer",            'D', 10,60, 0, 1, 1, new UnitType[] { UnitType.Armored },                           25,1850, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.BoltAxe,           new Weapon("Bolt Axe",          'B', 14,70, 5, 1, 2, new UnitType[] {},                                             30,1920, 1,                     new CharacterStatistics(), WeaponType.Axe) { isPhysical = false } },
            { ItemName.KillerAxe,         new Weapon("Killer Axe",        'C', 12,70, 30,1, 1, new UnitType[] {},                                             30,1860, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.Vegeance,          new Weapon("Vegeance",          'B', 16,75, 5, 1, 1, new UnitType[] {},                                             30,0,    1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.WolfBerg,          new Weapon("Wolf Berg",         'A', 18,75, 5, 1, 2, new UnitType[] {},                                             35,0,    1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.Hauteclere,        new Weapon("Hauteclere",        'A', 21,70, 5, 1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.Helswath,          new Weapon("Helswath",          'A', 18,60, 10,1, 2, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,0,0,5,0,0), WeaponType.Axe) },
            { ItemName.Armads,            new Weapon("Armads",            'A', 17,80, 10,1, 1, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,0,0,5,0,0), WeaponType.Axe) },
            { ItemName.Ladle,             new Weapon("Ladle",             'E', 1, 80, 0, 1, 1, new UnitType[] {},                                             20,100,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.GlassAxe,          new Weapon("Glass Axe",         'E', 15,65, 0, 1, 1, new UnitType[] {},                                             3, 600,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.ImposingAxe,       new Weapon("Imposing Axe",      'D', 14,35, 10,1, 1, new UnitType[] {},                                             10,830,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.VolantAxe,         new Weapon("Volant Axe",        'C', 8, 55, 0, 1, 2, new UnitType[] { UnitType.Flying },                            10,1510, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.SuperiorAxe,       new Weapon("Superior Axe",      'B', 15,60, 0, 1, 1, new UnitType[] {},                                             10,2150, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.OrsinsHatchet,     new Weapon("Orsin's Axe",       'D', 4, 85, 5, 1, 2, new UnitType[] {},                                             20,960,  1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.TitaniasAxe,       new Weapon("Titania's Axe",     'C', 12,80, 10,1, 1, new UnitType[] {},                                             20,1320, 1,                     new CharacterStatistics(), WeaponType.Axe) },
            { ItemName.HectorsAxe,        new Weapon("Hector's Axe",      'B', 15,75, 15,1, 1, new UnitType[] {},                                             15,2010, 1,                     new CharacterStatistics(0,2,0,0,0,2,0,0), WeaponType.Axe) },

            { ItemName.BronzeBow,         new Weapon("Bronze Bow",        'E', 3, 90, 0, 2, 2, new UnitType[] { UnitType.Flying },                            50,350,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.IronBow,           new Weapon("Iron Bow",          'D', 6, 85, 0, 2, 2, new UnitType[] { UnitType.Flying },                            40,560,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.SteelBow,          new Weapon("Steel Bow",         'C', 9, 80, 0, 2, 2, new UnitType[] { UnitType.Flying },                            35,910,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.SilverBow,         new Weapon("Silver Bow",        'B', 13,75, 0, 2, 2, new UnitType[] { UnitType.Flying },                            30,1560, 1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.BraveBow,          new Weapon("Brave Bow",         'A', 10,70, 0, 2, 2, new UnitType[] { UnitType.Flying },                            30,2220, 2,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.BlessedBow,        new Weapon("Blessed Bow",       'C', 11,70, 0, 2, 2, new UnitType[] { UnitType.Flying, UnitType.Monsters },         35,1540, 1,                     new CharacterStatistics(), WeaponType.Bow) { SelfHeal = 10 } },
            { ItemName.KillerBow,         new Weapon("Killer Bow",        'C', 10,80, 30,2, 2, new UnitType[] { UnitType.Flying },                            30,1680, 1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.Longbow,           new Weapon("Longbow",           'C', 9, 70, 0, 2, 3, new UnitType[] { UnitType.Flying },                            25,2150, 1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.Astra,             new Weapon("Astra",             'B', 14,75, 5, 2, 2, new UnitType[] { UnitType.Flying },                            30,0,    1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.Parthia,           new Weapon("Parthia",           'A', 19,95, 5, 2, 2, new UnitType[] { UnitType.Flying },                            25,0,    1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.Yewfelle,          new Weapon("Yewfelle",          'A', 15,85, 10,2, 2, new UnitType[] { UnitType.Flying },                            25,0,    1,                     new CharacterStatistics(0,0,0,0,5,0,0,0), WeaponType.Bow) },
            { ItemName.Nidhogg,           new Weapon("Nidhogg",           'A', 16,75, 10,2, 2, new UnitType[] { UnitType.Flying },                            25,0,    1,                     new CharacterStatistics(0,0,0,0,0,10,0,0,0), WeaponType.Bow) },
            { ItemName.DoubleBow,         new Weapon("Double Box",        'A', 13,70, 10,2, 3, new UnitType[] { UnitType.Flying },                            25,0,    1,                     new CharacterStatistics(0,5,0,0,0,0,0,0), WeaponType.Bow) },
            { ItemName.SlackBow,          new Weapon("Slack Bow",         'E', 1, 90, 0, 2, 2, new UnitType[] { UnitType.Flying },                            20,100,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.GlassBow,          new Weapon("Glass Bow",         'E', 13,75, 0, 2, 2, new UnitType[] { UnitType.Flying },                            3, 600,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.ToweringBow,       new Weapon("Towering Bow",      'D', 3, 80, 0, 2, 3, new UnitType[] { UnitType.Flying },                            10,810,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.UnderdogBow,       new Weapon("Underdog Bow",      'D', 9, 75, 5, 2, 2, new UnitType[] { UnitType.Flying },                            15,950,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.SuperiorBow,       new Weapon("Superior Bow",      'B', 13,70, 0, 2, 2, new UnitType[] { UnitType.Flying },                            10,2160, 1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.WoltsBow,          new Weapon("Wolt's Bow",        'C', 10,85, 5, 2, 2, new UnitType[] { UnitType.Flying },                            25,950,  1,                     new CharacterStatistics(), WeaponType.Bow) },
            { ItemName.InnesBow,          new Weapon("Innes' Bow",        'B', 13,115,10,2, 2, new UnitType[] { UnitType.Flying },                            15,1710, 1,                     new CharacterStatistics(), WeaponType.Bow) },

            { ItemName.Fire,              new Weapon("Fire",              'E', 2, 90, 0, 1, 2, new UnitType[] {},                                             45,540,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Elfire,            new Weapon("Elfire",            'D', 5, 85, 0, 1, 2, new UnitType[] {},                                             35,980,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Arcfire,           new Weapon("Arcfire",           'C', 8, 80, 0, 1, 2, new UnitType[] {},                                             30,1440, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Bolganone,         new Weapon("Bolganone",         'B', 12,75, 0, 1, 2, new UnitType[] {},                                             25,2000, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Valflame,          new Weapon("Valflame",          'A', 16,80, 10,1, 2, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,5,0,0,0,0,0), WeaponType.Tome)},
            { ItemName.Thunder,           new Weapon("Thunder",           'E', 3, 80, 5, 1, 2, new UnitType[] {},                                             45,630,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Elthunder,         new Weapon("Elthunder",         'D', 6, 75, 5, 1, 2, new UnitType[] {},                                             35,1050, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Arcthunder,        new Weapon("Arcthunder",        'C', 10,70, 10,1, 2, new UnitType[] {},                                             30,1620, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Thoron,            new Weapon("Thoron",            'B', 14,65, 10,1, 2, new UnitType[] {},                                             25,2200, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Mjolnir,           new Weapon("Mjölnir",           'A', 18,70, 20,1, 2, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(0,0,0,5,0,0,0,0), WeaponType.Tome)},
            { ItemName.Wind,              new Weapon("Wind",              'E', 1, 100,0, 1, 2, new UnitType[] { UnitType.Flying },                            45,450,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Elwind,            new Weapon("Elwind",            'D', 4, 95, 0, 1, 2, new UnitType[] { UnitType.Flying },                            35,910,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Arcwind,           new Weapon("Arcwind",           'C', 6, 90, 0, 1, 2, new UnitType[] { UnitType.Flying },                            30,1320, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Rexcalibur,        new Weapon("Rexcalibur",        'B', 10,85, 0, 1, 2, new UnitType[] { UnitType.Flying },                            25,1900, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Excalibur,         new Weapon("Excalibur",         'A', 13,100,30,1, 2, new UnitType[] { UnitType.Flying },                            25,0,    1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Forseti,           new Weapon("Forseti",           'A', 14,90, 10,1, 2, new UnitType[] { UnitType.Flying },                            25,0,    1,                     new CharacterStatistics(0,0,0,0,5,0,0,0), WeaponType.Tome)},
            { ItemName.BookofNaga,        new Weapon("Book of Naga",      'A', 15,80, 15,1, 2, new UnitType[] { UnitType.Dragons },                           25,0,    1,                     new CharacterStatistics(0,0,0,0,0,5,5,0), WeaponType.Tome)},
            { ItemName.Flux,              new Weapon("Flux",              'E', 5, 70, 0, 1, 2, new UnitType[] {},                                             45,540,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Nosferatu,         new Weapon("Nosferatu",         'D', 7, 65, 0, 1, 2, new UnitType[] {},                                             20,980,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Ruin,              new Weapon("Ruin",              'C', 4, 60, 50,1, 2, new UnitType[] {},                                             20,1380, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Waste,             new Weapon("Waste",             'B', 10,45, 0, 1, 2, new UnitType[] {},                                             30,2160, 2,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Goetia,            new Weapon("Goetia",            'A', 19,75, 10,1, 2, new UnitType[] {},                                             25,0,    1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.GrimasTruth,       new Weapon("Grima's Truth",     'B', 12,80, 0, 1, 2, new UnitType[] {},                                             -1,0,    1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Mire,              new Weapon("Mire",              'C', 10,65, 0, 3,10, new UnitType[] {},                                             10,2000, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.DyingBlaze,        new Weapon("Dying Blaze",       'E', 10,75, 0, 1, 2, new UnitType[] {},                                             3, 540,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.MicaiahsPyre,      new Weapon("Micaiah's Pyre",    'B', 13,85, 5, 1, 2, new UnitType[] {},                                             15,540,  1,                     new CharacterStatistics(0,0,0,0,0,2,2,0), WeaponType.Tome)},
            { ItemName.SuperiorJolt,      new Weapon("Superior Jolt",     'B', 14,60, 15,1, 2, new UnitType[] {},                                             10,2320, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.KatarinasBolt,     new Weapon("Katarina's Bolt",   'C', 11,75, 30,1, 2, new UnitType[] {},                                             20,1920, 1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.Wilderwind,        new Weapon("Wilderwind",        'D', 2, 70, 35,1, 2, new UnitType[] { UnitType.Flying },                            5, 760,  1,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.CelicasGale,       new Weapon("Celica's Gale",     'C', 4, 80, 5, 1, 2, new UnitType[] { UnitType.Flying },                            20,1720, 2,                     new CharacterStatistics(), WeaponType.Tome)},
            { ItemName.AversasNight,      new Weapon("Aversa's Night",    'B', 15,75, 0, 1, 2, new UnitType[] {},                                             10,2340, 1,                     new CharacterStatistics(), WeaponType.Tome)},

            { ItemName.Heal,              new Weapon("Heal",              'E', 0, 0, 0, 1, 1,  new UnitType[] {},                                             30,600,  1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Mend,              new Weapon("Mend",              'D', 0, 0, 0, 1, 1,  new UnitType[] {},                                             20,1000, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Physic,            new Weapon("Physic",            'C', 0, 0, 0, 1, -1, new UnitType[] {},                                             10,1800, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Recover,           new Weapon("Recover",           'B', 0, 0, 0, 1, 1,  new UnitType[] {},                                             15,1950, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Fortify,           new Weapon("Recover",           'B', 0, 0, 0, 1, -1, new UnitType[] {},                                             5, 2500, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.GoddessStaff,      new Weapon("Goddess Staff",     'E', 0, 0, 0, 1, -1, new UnitType[] {},                                             1, 0,    1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Rescue,            new Weapon("Rescue",            'D', 0, 0, 0, 1, -1, new UnitType[] {},                                             5, 1280, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Ward,              new Weapon("Ward",              'C', 0, 0, 0, 1, -1, new UnitType[] {},                                             5, 2100, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Hammerne,          new Weapon("Hammerne",          'B', 0, 0, 0, 1, 1,  new UnitType[] {},                                             1, 2000, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Kneader,           new Weapon("Kneader",           'E', 0, 0, 0, 1, 1,  new UnitType[] {},                                             20,100,  1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.BalmwoodStaff,     new Weapon("Balmwood Staff",    'D', 0, 0, 0, 1, 1,  new UnitType[] {},                                             15,1200, 1,                     new CharacterStatistics(), WeaponType.Staff)},
            { ItemName.Catharsis,         new Weapon("Catharsis",         'B', 0, 0, 0, 1, -1, new UnitType[] {},                                             5, 2100, 1,                     new CharacterStatistics(), WeaponType.Staff)},
        };


        public static Dictionary<ClassName, CharacterClass> Classes = new Dictionary<ClassName, CharacterClass>()
        {
            { ClassName.Lord,           new CharacterClass("Lord",          new WeaponType[] { WeaponType.Sword },                                  new UnitType[] { },                                     new CharacterStatistics(18, 6, 0, 5, 7, 7, 0, 5)) },
            { ClassName.GreatLord,      new CharacterClass("Great Lord",    new WeaponType[] { WeaponType.Sword, WeaponType.Lance },                new UnitType[] { },                                     new CharacterStatistics(23, 10, 0, 7, 9, 10, 3, 6)) },
            { ClassName.Tactician,      new CharacterClass("Tactician",     new WeaponType[] { WeaponType.Sword, WeaponType.Tome },                 new UnitType[] { },                                     new CharacterStatistics(16, 4, 3, 5, 5, 5, 3, 5)) },
            { ClassName.Grandmaster,    new CharacterClass("Grandmaster",   new WeaponType[] { WeaponType.Sword, WeaponType.Tome },                 new UnitType[] { },                                     new CharacterStatistics(20, 7, 6, 7, 7, 7, 5, 6)) },
            { ClassName.Cavalier,       new CharacterClass("Cavalier",      new WeaponType[] { WeaponType.Sword, WeaponType.Lance },                new UnitType[] { UnitType.Beasts },                     new CharacterStatistics(18, 6, 0, 5, 6, 7, 0, 7)) },
            { ClassName.Paladin,        new CharacterClass("Paladin",       new WeaponType[] { WeaponType.Sword, WeaponType.Lance },                new UnitType[] { UnitType.Beasts },                     new CharacterStatistics(25, 9, 1, 7, 8, 10, 6, 8)) },
            { ClassName.GreatKnight,    new CharacterClass("Great Knight",  new WeaponType[] { WeaponType.Sword, WeaponType.Lance, WeaponType.Axe },new UnitType[] { UnitType.Beasts, UnitType.Armored },   new CharacterStatistics(26, 11, 0, 6, 5, 14, 1, 7)) },
            { ClassName.Knight,         new CharacterClass("Knight",        new WeaponType[] { WeaponType.Lance },                                  new UnitType[] { UnitType.Armored },                    new CharacterStatistics(18, 8, 0, 4, 2, 11, 0, 4)) },
            { ClassName.General,        new CharacterClass("General",       new WeaponType[] { WeaponType.Lance, WeaponType.Axe },                  new UnitType[] { UnitType.Armored },                    new CharacterStatistics(28, 12, 0, 7, 4, 15, 3, 5)) },
            { ClassName.Myrmidon,       new CharacterClass("Myrmidon",      new WeaponType[] { WeaponType.Sword },                                  new UnitType[] { },                                     new CharacterStatistics(16, 4, 1, 9, 10, 4, 1, 5)) },
            { ClassName.Swordmaster,    new CharacterClass("Swordmaster",   new WeaponType[] { WeaponType.Sword },                                  new UnitType[] { },                                     new CharacterStatistics(20, 7, 2, 11, 13, 6, 4, 6)) },
            { ClassName.Mercenary,      new CharacterClass("Mercenary",     new WeaponType[] { WeaponType.Sword },                                  new UnitType[] { },                                     new CharacterStatistics(18, 5, 0, 8, 7, 5, 0, 5)) },
            { ClassName.Hero,           new CharacterClass("Hero",          new WeaponType[] { WeaponType.Sword, WeaponType.Axe },                  new UnitType[] { },                                     new CharacterStatistics(22, 8, 1, 11, 10, 8, 3, 6)) },
            { ClassName.Fighter,        new CharacterClass("Fighter",       new WeaponType[] { WeaponType.Axe },                                    new UnitType[] { },                                     new CharacterStatistics(20, 8, 0, 5, 5, 4, 0, 5)) },
            { ClassName.Warrior,        new CharacterClass("Warrior",       new WeaponType[] { WeaponType.Axe, WeaponType.Bow },                    new UnitType[] { },                                     new CharacterStatistics(28, 12, 0, 8, 7, 7, 3, 6)) },
            { ClassName.Barbarian,      new CharacterClass("Barbarian",     new WeaponType[] { WeaponType.Axe },                                    new UnitType[] { },                                     new CharacterStatistics(22, 8, 0, 3, 8, 3, 0, 5)) },
            { ClassName.Berserker,      new CharacterClass("Berserker",     new WeaponType[] { WeaponType.Axe },                                    new UnitType[] { },                                     new CharacterStatistics(30, 13, 0, 5, 11, 5, 1, 6)) },
            { ClassName.Archer,         new CharacterClass("Archer",        new WeaponType[] { WeaponType.Bow },                                    new UnitType[] { },                                     new CharacterStatistics(16, 5, 0, 8, 6, 5, 0, 5)) },
            { ClassName.Sniper,         new CharacterClass("Sniper",        new WeaponType[] { WeaponType.Bow },                                    new UnitType[] { },                                     new CharacterStatistics(20, 7, 1, 12, 9, 10, 3, 6)) },
            { ClassName.BowKnight,      new CharacterClass("Bow Knight",    new WeaponType[] { WeaponType.Sword, WeaponType.Bow },                  new UnitType[] { },                                     new CharacterStatistics(24, 8, 0, 10, 10, 6, 2, 8)) },
            { ClassName.Thief,          new CharacterClass("Thief",         new WeaponType[] { WeaponType.Sword },                                  new UnitType[] { },                                     new CharacterStatistics(16, 3, 0, 6, 8, 2, 0, 5)) },
            { ClassName.Assassin,       new CharacterClass("Assassin",      new WeaponType[] { WeaponType.Sword, WeaponType.Bow },                  new UnitType[] { },                                     new CharacterStatistics(21, 8, 0, 13, 12, 5, 1, 6)) },
            { ClassName.Trickster,      new CharacterClass("Trickster",     new WeaponType[] { WeaponType.Sword, WeaponType.Staff },                new UnitType[] { },                                     new CharacterStatistics(19, 4, 4, 10, 11, 3, 5, 6)) },
            { ClassName.PegasusKnight,  new CharacterClass("Pegasus Knight",new WeaponType[] { WeaponType.Lance },                                  new UnitType[] { UnitType.Flying },                     new CharacterStatistics(16, 4, 2, 7, 8 ,4, 6, 7)) },
            { ClassName.FalconKnight,   new CharacterClass("Falcon Knight", new WeaponType[] { WeaponType.Lance, WeaponType.Staff },                new UnitType[] { UnitType.Flying },                     new CharacterStatistics(20, 6, 3, 10, 11, 6, 9, 8)) },
            { ClassName.DarkFlier,      new CharacterClass("Dark Flier",    new WeaponType[] { WeaponType.Lance, WeaponType.Tome },                 new UnitType[] { UnitType.Flying },                     new CharacterStatistics(19, 5, 6, 8, 10, 5, 9, 8)) },
            { ClassName.WyvernRider,    new CharacterClass("Wyvern Rider",  new WeaponType[] { WeaponType.Axe },                                    new UnitType[] { UnitType.Flying, UnitType.Dragons },   new CharacterStatistics(19, 7, 0 ,6, 5, 8, 0, 7)) },
            { ClassName.WyvernLord,     new CharacterClass("Wyvern Lord",   new WeaponType[] { WeaponType.Lance, WeaponType.Axe },                  new UnitType[] { UnitType.Flying, UnitType.Dragons },   new CharacterStatistics(24, 11, 0, 8, 7, 11, 3, 8)) },
            { ClassName.GriffonRider,   new CharacterClass("Griffon Rider", new WeaponType[] { WeaponType.Axe },                                    new UnitType[] { UnitType.Flying },                     new CharacterStatistics(22, 9, 0, 10, 9, 8, 3, 8)) },
            { ClassName.Mage,           new CharacterClass("Mage",          new WeaponType[] { WeaponType.Tome },                                   new UnitType[] { },                                     new CharacterStatistics(16, 0, 4, 3, 4, 2, 3, 5)) },
            { ClassName.Sage,           new CharacterClass("Sage",          new WeaponType[] { WeaponType.Tome, WeaponType.Staff },                 new UnitType[] { },                                     new CharacterStatistics(20, 1, 7, 5, 7, 4, 5, 6)) },
            { ClassName.DarkMage,       new CharacterClass("Dark Mage",     new WeaponType[] { WeaponType.Tome },                                   new UnitType[] { },                                     new CharacterStatistics(18, 1, 3, 2, 3, 4, 4, 5)) },
            { ClassName.Sorcerer,       new CharacterClass("Sorcerer",      new WeaponType[] { WeaponType.Tome },                                   new UnitType[] { },                                     new CharacterStatistics(23, 2, 6, 4, 4, 7, 7, 6)) },
            { ClassName.DarkKnight,     new CharacterClass("Dark Knight",   new WeaponType[] { WeaponType.Sword, WeaponType.Tome },                 new UnitType[] { },                                     new CharacterStatistics(25, 2, 6, 4, 4, 7, 7, 6)) },
            { ClassName.Cleric,         new CharacterClass("Cleric",        new WeaponType[] { WeaponType.Staff },                                  new UnitType[] { },                                     new CharacterStatistics(16, 0, 3, 2, 4, 1, 6, 5)) },
            { ClassName.Priest,         new CharacterClass("Priest",        new WeaponType[] { WeaponType.Staff },                                  new UnitType[] { },                                     new CharacterStatistics(16, 0, 3, 2, 4, 1, 6, 5)) },
            { ClassName.WarMonk,        new CharacterClass("War Monk",      new WeaponType[] { WeaponType.Staff, WeaponType.Axe },                  new UnitType[] { },                                     new CharacterStatistics(24, 5, 5, 4, 8, 3, 8, 8)) },
            { ClassName.Troubadour,     new CharacterClass("Troubadour",    new WeaponType[] { WeaponType.Staff },                                  new UnitType[] { UnitType.Beasts },                     new CharacterStatistics(16, 0, 3, 2, 5, 1, 5, 7)) },
            { ClassName.Valkyrie,       new CharacterClass("Valkyrie",      new WeaponType[] { WeaponType.Tome, WeaponType.Staff },                 new UnitType[] { UnitType.Beasts },                     new CharacterStatistics(19, 0, 5, 4, 8, 3, 8, 8)) },
            { ClassName.Villager,       new CharacterClass("Villager",      new WeaponType[] { WeaponType.Lance },                                  new UnitType[] { },                                     new CharacterStatistics(16, 1, 0, 1, 1, 1, 0, 5)) },
            { ClassName.Dancer,         new CharacterClass("Dancer",        new WeaponType[] { WeaponType.Sword },                                  new UnitType[] { },                                     new CharacterStatistics(16, 1, 1, 5, 8, 3, 1, 5)) },
            { ClassName.Lodestar,       new CharacterClass("Lodestar",      new WeaponType[] { WeaponType.Sword },                                  new UnitType[] { },                                     new CharacterStatistics(21, 9, 1, 10, 10, 8, 4, 6)) },
            { ClassName.DreadFighter,   new CharacterClass("Dread Fighter", new WeaponType[] { WeaponType.Sword, WeaponType.Axe, WeaponType.Tome }, new UnitType[] { },                                     new CharacterStatistics(22, 8, 4, 7, 9, 7, 10, 6)) },
            { ClassName.Soldier,        new CharacterClass("Soldier",       new WeaponType[] { WeaponType.Sword, WeaponType.Lance },                new UnitType[] { },                                     new CharacterStatistics(18, 3, 0, 3, 3, 3, 0, 5)) },
            { ClassName.Conqueror,      new CharacterClass("Conqueror",     new WeaponType[] { WeaponType.Sword, WeaponType.Lance, WeaponType.Axe },new UnitType[] { },                                     new CharacterStatistics(24, 10, 3, 9, 8, 12, 5, 8)) }
        };
    }
}
